
development:
  adapter: postgresql
  encoding: unicode
  database: race_tweeter_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: race_tweeter_test
  pool: 5
  host: localhost
