
development:
  adapter: postgresql
  encoding: unicode
  database: race-tracker_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: race-tracker_test
  pool: 5
  host: localhost
